# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/manu/Desktop/tallerTpGtupal

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/manu/Desktop/tallerTpGtupal

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/manu/Desktop/tallerTpGtupal/CMakeFiles /home/manu/Desktop/tallerTpGtupal/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/manu/Desktop/tallerTpGtupal/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named sdlpp-hello

# Build rule for target.
sdlpp-hello: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sdlpp-hello
.PHONY : sdlpp-hello

# fast build rule for target.
sdlpp-hello/fast:
	$(MAKE) -f CMakeFiles/sdlpp-hello.dir/build.make CMakeFiles/sdlpp-hello.dir/build
.PHONY : sdlpp-hello/fast

#=============================================================================
# Target rules for targets named SDL2pp

# Build rule for target.
SDL2pp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SDL2pp
.PHONY : SDL2pp

# fast build rule for target.
SDL2pp/fast:
	$(MAKE) -f libs/libSDL2pp/CMakeFiles/SDL2pp.dir/build.make libs/libSDL2pp/CMakeFiles/SDL2pp.dir/build
.PHONY : SDL2pp/fast

src/client/board.o: src/client/board.cpp.o

.PHONY : src/client/board.o

# target to build an object file
src/client/board.cpp.o:
	$(MAKE) -f CMakeFiles/sdlpp-hello.dir/build.make CMakeFiles/sdlpp-hello.dir/src/client/board.cpp.o
.PHONY : src/client/board.cpp.o

src/client/board.i: src/client/board.cpp.i

.PHONY : src/client/board.i

# target to preprocess a source file
src/client/board.cpp.i:
	$(MAKE) -f CMakeFiles/sdlpp-hello.dir/build.make CMakeFiles/sdlpp-hello.dir/src/client/board.cpp.i
.PHONY : src/client/board.cpp.i

src/client/board.s: src/client/board.cpp.s

.PHONY : src/client/board.s

# target to generate assembly for a file
src/client/board.cpp.s:
	$(MAKE) -f CMakeFiles/sdlpp-hello.dir/build.make CMakeFiles/sdlpp-hello.dir/src/client/board.cpp.s
.PHONY : src/client/board.cpp.s

src/client/mainSdlHello.o: src/client/mainSdlHello.cpp.o

.PHONY : src/client/mainSdlHello.o

# target to build an object file
src/client/mainSdlHello.cpp.o:
	$(MAKE) -f CMakeFiles/sdlpp-hello.dir/build.make CMakeFiles/sdlpp-hello.dir/src/client/mainSdlHello.cpp.o
.PHONY : src/client/mainSdlHello.cpp.o

src/client/mainSdlHello.i: src/client/mainSdlHello.cpp.i

.PHONY : src/client/mainSdlHello.i

# target to preprocess a source file
src/client/mainSdlHello.cpp.i:
	$(MAKE) -f CMakeFiles/sdlpp-hello.dir/build.make CMakeFiles/sdlpp-hello.dir/src/client/mainSdlHello.cpp.i
.PHONY : src/client/mainSdlHello.cpp.i

src/client/mainSdlHello.s: src/client/mainSdlHello.cpp.s

.PHONY : src/client/mainSdlHello.s

# target to generate assembly for a file
src/client/mainSdlHello.cpp.s:
	$(MAKE) -f CMakeFiles/sdlpp-hello.dir/build.make CMakeFiles/sdlpp-hello.dir/src/client/mainSdlHello.cpp.s
.PHONY : src/client/mainSdlHello.cpp.s

src/client/menu.o: src/client/menu.cpp.o

.PHONY : src/client/menu.o

# target to build an object file
src/client/menu.cpp.o:
	$(MAKE) -f CMakeFiles/sdlpp-hello.dir/build.make CMakeFiles/sdlpp-hello.dir/src/client/menu.cpp.o
.PHONY : src/client/menu.cpp.o

src/client/menu.i: src/client/menu.cpp.i

.PHONY : src/client/menu.i

# target to preprocess a source file
src/client/menu.cpp.i:
	$(MAKE) -f CMakeFiles/sdlpp-hello.dir/build.make CMakeFiles/sdlpp-hello.dir/src/client/menu.cpp.i
.PHONY : src/client/menu.cpp.i

src/client/menu.s: src/client/menu.cpp.s

.PHONY : src/client/menu.s

# target to generate assembly for a file
src/client/menu.cpp.s:
	$(MAKE) -f CMakeFiles/sdlpp-hello.dir/build.make CMakeFiles/sdlpp-hello.dir/src/client/menu.cpp.s
.PHONY : src/client/menu.cpp.s

src/client/piece.o: src/client/piece.cpp.o

.PHONY : src/client/piece.o

# target to build an object file
src/client/piece.cpp.o:
	$(MAKE) -f CMakeFiles/sdlpp-hello.dir/build.make CMakeFiles/sdlpp-hello.dir/src/client/piece.cpp.o
.PHONY : src/client/piece.cpp.o

src/client/piece.i: src/client/piece.cpp.i

.PHONY : src/client/piece.i

# target to preprocess a source file
src/client/piece.cpp.i:
	$(MAKE) -f CMakeFiles/sdlpp-hello.dir/build.make CMakeFiles/sdlpp-hello.dir/src/client/piece.cpp.i
.PHONY : src/client/piece.cpp.i

src/client/piece.s: src/client/piece.cpp.s

.PHONY : src/client/piece.s

# target to generate assembly for a file
src/client/piece.cpp.s:
	$(MAKE) -f CMakeFiles/sdlpp-hello.dir/build.make CMakeFiles/sdlpp-hello.dir/src/client/piece.cpp.s
.PHONY : src/client/piece.cpp.s

src/client/spot.o: src/client/spot.cpp.o

.PHONY : src/client/spot.o

# target to build an object file
src/client/spot.cpp.o:
	$(MAKE) -f CMakeFiles/sdlpp-hello.dir/build.make CMakeFiles/sdlpp-hello.dir/src/client/spot.cpp.o
.PHONY : src/client/spot.cpp.o

src/client/spot.i: src/client/spot.cpp.i

.PHONY : src/client/spot.i

# target to preprocess a source file
src/client/spot.cpp.i:
	$(MAKE) -f CMakeFiles/sdlpp-hello.dir/build.make CMakeFiles/sdlpp-hello.dir/src/client/spot.cpp.i
.PHONY : src/client/spot.cpp.i

src/client/spot.s: src/client/spot.cpp.s

.PHONY : src/client/spot.s

# target to generate assembly for a file
src/client/spot.cpp.s:
	$(MAKE) -f CMakeFiles/sdlpp-hello.dir/build.make CMakeFiles/sdlpp-hello.dir/src/client/spot.cpp.s
.PHONY : src/client/spot.cpp.s

src/server/bishop.o: src/server/bishop.cpp.o

.PHONY : src/server/bishop.o

# target to build an object file
src/server/bishop.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/bishop.cpp.o
.PHONY : src/server/bishop.cpp.o

src/server/bishop.i: src/server/bishop.cpp.i

.PHONY : src/server/bishop.i

# target to preprocess a source file
src/server/bishop.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/bishop.cpp.i
.PHONY : src/server/bishop.cpp.i

src/server/bishop.s: src/server/bishop.cpp.s

.PHONY : src/server/bishop.s

# target to generate assembly for a file
src/server/bishop.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/bishop.cpp.s
.PHONY : src/server/bishop.cpp.s

src/server/board.o: src/server/board.cpp.o

.PHONY : src/server/board.o

# target to build an object file
src/server/board.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/board.cpp.o
.PHONY : src/server/board.cpp.o

src/server/board.i: src/server/board.cpp.i

.PHONY : src/server/board.i

# target to preprocess a source file
src/server/board.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/board.cpp.i
.PHONY : src/server/board.cpp.i

src/server/board.s: src/server/board.cpp.s

.PHONY : src/server/board.s

# target to generate assembly for a file
src/server/board.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/board.cpp.s
.PHONY : src/server/board.cpp.s

src/server/king.o: src/server/king.cpp.o

.PHONY : src/server/king.o

# target to build an object file
src/server/king.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/king.cpp.o
.PHONY : src/server/king.cpp.o

src/server/king.i: src/server/king.cpp.i

.PHONY : src/server/king.i

# target to preprocess a source file
src/server/king.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/king.cpp.i
.PHONY : src/server/king.cpp.i

src/server/king.s: src/server/king.cpp.s

.PHONY : src/server/king.s

# target to generate assembly for a file
src/server/king.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/king.cpp.s
.PHONY : src/server/king.cpp.s

src/server/knight.o: src/server/knight.cpp.o

.PHONY : src/server/knight.o

# target to build an object file
src/server/knight.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/knight.cpp.o
.PHONY : src/server/knight.cpp.o

src/server/knight.i: src/server/knight.cpp.i

.PHONY : src/server/knight.i

# target to preprocess a source file
src/server/knight.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/knight.cpp.i
.PHONY : src/server/knight.cpp.i

src/server/knight.s: src/server/knight.cpp.s

.PHONY : src/server/knight.s

# target to generate assembly for a file
src/server/knight.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/knight.cpp.s
.PHONY : src/server/knight.cpp.s

src/server/main.o: src/server/main.cpp.o

.PHONY : src/server/main.o

# target to build an object file
src/server/main.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/main.cpp.o
.PHONY : src/server/main.cpp.o

src/server/main.i: src/server/main.cpp.i

.PHONY : src/server/main.i

# target to preprocess a source file
src/server/main.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/main.cpp.i
.PHONY : src/server/main.cpp.i

src/server/main.s: src/server/main.cpp.s

.PHONY : src/server/main.s

# target to generate assembly for a file
src/server/main.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/main.cpp.s
.PHONY : src/server/main.cpp.s

src/server/pawn.o: src/server/pawn.cpp.o

.PHONY : src/server/pawn.o

# target to build an object file
src/server/pawn.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/pawn.cpp.o
.PHONY : src/server/pawn.cpp.o

src/server/pawn.i: src/server/pawn.cpp.i

.PHONY : src/server/pawn.i

# target to preprocess a source file
src/server/pawn.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/pawn.cpp.i
.PHONY : src/server/pawn.cpp.i

src/server/pawn.s: src/server/pawn.cpp.s

.PHONY : src/server/pawn.s

# target to generate assembly for a file
src/server/pawn.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/pawn.cpp.s
.PHONY : src/server/pawn.cpp.s

src/server/piece.o: src/server/piece.cpp.o

.PHONY : src/server/piece.o

# target to build an object file
src/server/piece.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/piece.cpp.o
.PHONY : src/server/piece.cpp.o

src/server/piece.i: src/server/piece.cpp.i

.PHONY : src/server/piece.i

# target to preprocess a source file
src/server/piece.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/piece.cpp.i
.PHONY : src/server/piece.cpp.i

src/server/piece.s: src/server/piece.cpp.s

.PHONY : src/server/piece.s

# target to generate assembly for a file
src/server/piece.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/piece.cpp.s
.PHONY : src/server/piece.cpp.s

src/server/queen.o: src/server/queen.cpp.o

.PHONY : src/server/queen.o

# target to build an object file
src/server/queen.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/queen.cpp.o
.PHONY : src/server/queen.cpp.o

src/server/queen.i: src/server/queen.cpp.i

.PHONY : src/server/queen.i

# target to preprocess a source file
src/server/queen.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/queen.cpp.i
.PHONY : src/server/queen.cpp.i

src/server/queen.s: src/server/queen.cpp.s

.PHONY : src/server/queen.s

# target to generate assembly for a file
src/server/queen.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/queen.cpp.s
.PHONY : src/server/queen.cpp.s

src/server/rook.o: src/server/rook.cpp.o

.PHONY : src/server/rook.o

# target to build an object file
src/server/rook.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/rook.cpp.o
.PHONY : src/server/rook.cpp.o

src/server/rook.i: src/server/rook.cpp.i

.PHONY : src/server/rook.i

# target to preprocess a source file
src/server/rook.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/rook.cpp.i
.PHONY : src/server/rook.cpp.i

src/server/rook.s: src/server/rook.cpp.s

.PHONY : src/server/rook.s

# target to generate assembly for a file
src/server/rook.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/rook.cpp.s
.PHONY : src/server/rook.cpp.s

src/server/square.o: src/server/square.cpp.o

.PHONY : src/server/square.o

# target to build an object file
src/server/square.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/square.cpp.o
.PHONY : src/server/square.cpp.o

src/server/square.i: src/server/square.cpp.i

.PHONY : src/server/square.i

# target to preprocess a source file
src/server/square.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/square.cpp.i
.PHONY : src/server/square.cpp.i

src/server/square.s: src/server/square.cpp.s

.PHONY : src/server/square.s

# target to generate assembly for a file
src/server/square.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/square.cpp.s
.PHONY : src/server/square.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... server"
	@echo "... sdlpp-hello"
	@echo "... SDL2pp"
	@echo "... src/client/board.o"
	@echo "... src/client/board.i"
	@echo "... src/client/board.s"
	@echo "... src/client/mainSdlHello.o"
	@echo "... src/client/mainSdlHello.i"
	@echo "... src/client/mainSdlHello.s"
	@echo "... src/client/menu.o"
	@echo "... src/client/menu.i"
	@echo "... src/client/menu.s"
	@echo "... src/client/piece.o"
	@echo "... src/client/piece.i"
	@echo "... src/client/piece.s"
	@echo "... src/client/spot.o"
	@echo "... src/client/spot.i"
	@echo "... src/client/spot.s"
	@echo "... src/server/bishop.o"
	@echo "... src/server/bishop.i"
	@echo "... src/server/bishop.s"
	@echo "... src/server/board.o"
	@echo "... src/server/board.i"
	@echo "... src/server/board.s"
	@echo "... src/server/king.o"
	@echo "... src/server/king.i"
	@echo "... src/server/king.s"
	@echo "... src/server/knight.o"
	@echo "... src/server/knight.i"
	@echo "... src/server/knight.s"
	@echo "... src/server/main.o"
	@echo "... src/server/main.i"
	@echo "... src/server/main.s"
	@echo "... src/server/pawn.o"
	@echo "... src/server/pawn.i"
	@echo "... src/server/pawn.s"
	@echo "... src/server/piece.o"
	@echo "... src/server/piece.i"
	@echo "... src/server/piece.s"
	@echo "... src/server/queen.o"
	@echo "... src/server/queen.i"
	@echo "... src/server/queen.s"
	@echo "... src/server/rook.o"
	@echo "... src/server/rook.i"
	@echo "... src/server/rook.s"
	@echo "... src/server/square.o"
	@echo "... src/server/square.i"
	@echo "... src/server/square.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

